### ISSUE TITLE
Mojang Changed API Which Tells If Account Is Secured or Not.

### ISSUE THREAD

**Issue by CripWalked** [CmlLib/MojangAPI#1]

**Comment by AlphaBs** [comment]
do you know what's changed?

**Comment by Hi-ImKyle** [comment]
I checked, the API doesn't look like it's changed, the endpoints are the same and the data sent is fine. It's just when it goes to check if the account is secured or not, there's an error with `QuestionFlow.CheckTrusted`

EDIT: That being said, when logging into the website and trusted returns false, checked via Fiddler, the security questions don't prompt anyway. Maybe a Mojang issue?

**Comment by AlphaBs** [comment]
fixed in 1.0.3
No API was changed but the code has some problems.
I can't test the security questions in website because my IP was already trusted..
