### ISSUE TITLE
How to do Xbox Account Authentication

### ISSUE THREAD

**Issue by AAM1075** [CmlLib/MojangAPI#2]
I'm making a portable Minecraft launcher, and I want to implement Xbox Account Authentication. I've looked through this API, but haven't found anything helpful. In the example program there is something called "Mojang" and "MojangAuth", but I haven't found something like "MicrosoftAuth" or "XboxAuth".

How should I go about this?

**Comment by AlphaBs** [comment]
use this library
https://github.com/CmlLib/CmlLib.Core.Auth.Microsoft
