### ISSUE TITLE
Player Attributes API not working with this library

### ISSUE THREAD

**Issue by EvanEvan-17** [CmlLib/MojangAPI#3]
Hello, I've trying to get Player Attributes with this library, but it is not working, it says 401: Unauthorized. It looks like the correct endpoint is not `/players/attributes` but `/player/attributes`. I've also trying to call it directly with RestSharp and deserialize the result to the Player Attributes model that is on this library, but it is also not working. Actually I use that API to get player's Xbox Privacy Settings if it not applied automatically. I also have some question:

**Does the user Xbox Privacy Settings automatically applied on my launcher without any additional coding?
If yes, then this issue will be solved for now.**

I've a screenshot for this
<img width="670" alt="Mojang API Player Attributes error" src="https://user-images.githubusercontent.com/63246541/183272588-61eee6fa-aff6-41e9-a0e3-5ab814d6603b.png">
.

**Comment by AlphaBs** [comment]
okay thank you for reporting. 

There were cases where some users failed to log in with an error 'Not authenticated with Minecraft.net' when connecting to the online-mode server. I found that multiplayer was disabled in the user's xbox privacy settings.

So at least disabling multiplay in xbox privacy setting seems to work without any coding on the launcher.

**Comment by EvanEvan-17** [comment]
Can you fix it? Does it also disable chat in Minecraft when the user's Xbox Privacy Settings doesn't allow chat?

**Comment by AlphaBs** [comment]
fixed on 1.2.1

**Comment by EvanEvan-17** [comment]
This has been fixed. Thank you.
