### ISSUE TITLE
Well the authentication thing just doesn't work...

### ISSUE THREAD

**Issue by xauuzd** [CmlLib/MojangAPI#4]
![image](https://user-images.githubusercontent.com/84229419/184552055-7b4c2cfb-eb1d-4603-8f44-c38c8e4cd09c.png)

Tried out the Authentication Example from https://github.com/CmlLib/MojangAPI/blob/master/docs/MojangAuth.md

**Comment by AlphaBs** [comment]
you can await methods only in async method. 

example:
```csharp
async Task this_is_async_method()
{
    MojangAuth auth = ~~~~~~;
    var res = await auth.Authenticate(~~~);
}
```
