### ISSUE TITLE
MojangAPI.MojangException: 'Not Found, The server has not found anything matching the request URI'

### ISSUE THREAD

**Issue by xauuzd** [CmlLib/MojangAPI#5]
![image](https://github.com/CmlLib/MojangAPI/assets/84229419/e7eb27d1-5a0b-4625-87fa-0ed83bacfbde)

Does this library no longer work?

**Comment by AlphaBs** [comment]
That endpoint has been deprecated. [link](https://wiki.vg/Mojang_API#UUID_to_Name_History_.28Removed.29) 

Everything else would work fine. I'll update the docs

**Comment by xauuzd** [comment]
Okay, thank you.

**Comment by xauuzd** [comment]
Can you also update this https://alphabs.gitbook.io/cmllib/cmllib.core/installer/forge-installer ?

The link https://github.com/CmlLib/CmlLib.Core-wiki/blob/master/en/cmllib.core/Installer/broken-reference/README.md
is invalid, and I want to know how I can automate installing forge.

**Comment by AlphaBs** [comment]
all broken links fixed
